# This is a basic workflow to help you get started with boman.ai

name: Bomanai Scanner Prod
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  Boman-scan:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Install packages
        run: sudo pip install boman-cli
      - name: Run scan
        env:
          API_KEY: ${{ secrets.Goat_vul }}
        run: sudo boman-cli -a run -at dcb126ca-867c-4308-9eeb-6c473fc7baa5 -ct 41bb9111-e57f-43d9-aa15-8c2e751ddb36
        # run: sudo boman-cli-uat -a run -u https://qa.boman.ai
